### ISSUE TITLE
Allow opening app detail pages in the background

### ISSUE THREAD

**Issue by nikwen** [bhdouglass/uappexplorer#43] opened 2015-05-28 20:24 UTC
Open uappexplorer.com/apps in the webbrowser app. It would be nice if the usual context menu with the "Open link in background tab" entry (it might be possible that this feature isn't available on the stable channel yet) showed up when long-pressing an app icon/name. Instead, I only see a "Copy" entry.

**Comment by bhdouglass** [comment] 2015-05-28 22:55
Do other websites show the "Open link in background tab"? Its just a normal HTML link so if the feature is available I would assume it would work for those links.

**Comment by nikwen** [comment] 2015-05-29 10:13
It works on most pages, yes. Take Github as an example.
However, there seem to be some issues when the link consists of an image.
I think that even if you don't have that option, you should be able to test this on your device as it should nevertheless display a "Open link in new tab" option and I'm not seeing that when long-pressing on an app.
It does work though when clicking on the Webapp, Twitter and RSS links at the bottom of the page.

**Comment by bhdouglass** [comment] 2015-05-31 04:41
I think I see the problem, it doesn't like all the extra html elements under the link tag. If you open the context menu to the side of the app (not on the image/text) where it is still part of the link it behaves properly. You may want to open a bug against the web browser. But I'll think about a way to work around it.

**Comment by nikwen** [comment] 2015-06-01 20:16
Ok, I'll do that. :)

**Comment by nikwen** [comment] 2015-06-01 20:23
Check out https://bugs.launchpad.net/ubuntu/+source/webbrowser-app/+bug/1460809.
Since you wanted to work around it, I decided to use another page as an example. ;)

**Comment by bhdouglass** [comment] 2015-06-02 04:31
I just added my "me too" over there, thanks!

**Comment by nikwen** [comment] 2015-06-02 10:21
Thank you, too.

**Comment by bhdouglass** [comment] 2015-06-05 02:05
The bug you filed was a duplicate of https://bugs.launchpad.net/oxide/+bug/1326070, it seems to be close to completion. So I'm going to wait a bit to find a work around.

**Comment by nikwen** [comment] 2015-06-08 19:40
Saw that, thanks.

**Comment by bhdouglass** [comment] 2015-09-18 19:55
@nikwen the launchpad bug says "Fix released" have you tried using the latest version of oxide yet?

**Comment by nikwen** [comment] 2015-09-18 20:22
Just checked it on today's release of rc-proposed. It's working perfectly now!

![screenshot20150918_222157552](https://cloud.githubusercontent.com/assets/3309657/9970151/c3adb68a-5e53-11e5-86cc-cfdeea371896.png)

**Comment by bhdouglass** [comment] 2015-09-19 04:09
Awesome!

**Closed by bhdouglass** 2015-09-19 04:09 UTC
